name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/main.yml"
      - "packages/agency-blog-modern/**"
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: packages/agency-blog-modern
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
      GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GOOGLE_ANALYTICS_TRACKING_ID }}
      SITE_URL: ${{ secrets.SITE_URL }}
      MAILCHIMP_ENDPOINT: ${{ secrets.MAILCHIMP_ENDPOINT }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup kernel for gatsby, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install package
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build --prefix-paths

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/agency-blog-modern/public
          cname: bursaintegralyonetim.com
